### ISSUE TITLE
Port removed

### ISSUE THREAD

**Issue by brayniverse** [FacultyCreative/ngActiveResource#21]
How come you're removing `:` from the url [here](https://github.com/FacultyCreative/ngActiveResource/blob/dec88238269c8d8918fbab7f9fbb7e21e99e331e/lib/angular-resource/base/base.js#L438)? It only seems to remove my port number. 

``` javascript
url = url.replace(/\:\w+/, '');
```

I didn't want to make a pull request because I don't know why it's there in the first place.

**Comment by brettshollenberger** [comment]
That's a good question. I thought I had tested for the port, but I will look at this in a moment :)

**Comment by facultymatt** [comment]
It's worth noting older versions of angular had issues where the port
(because it also started with `:`) was stripped from the url. The way to
get around it is outlined here: http://stackoverflow.com/a/19800965/1738217

This is fixed in new angular but look like we have a similar regEx in
ngActiveResource that causes trouble.

On Wed, Feb 19, 2014 at 3:56 PM, Brett Cassette notifications@github.comwrote:

> That's a good question. I thought I had tested for the port, but I will
> look at this in a moment :)
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/FacultyCreative/ngActiveResource/issues/21#issuecomment-35547406
> .

## 

_Matt MillerCreative Developerm *609.335.4417
*twt_ @mattmillerart http://twitter.com/#!/mattmillerart

## 

faculty
_twt_ @facultycreative http://twitter.com/#!/facultycreative
_w_ www.facultycreative.com

2424 E. York Street
Suite 233
Philadelphia Pa. 19125
