### ISSUE TITLE
Tidy Up Mission

### ISSUE THREAD

**Issue by brayniverse** [FacultyCreative/ngActiveResource#34]
Hey @brettshollenberger,

I have made some contributions & pull requests regarding the addition of new features and think this may have been a mistake, at least for the time being, because I've been very busy at work and haven't had the chance to follow these up yet. That's not the only reason I think they were a mistake, I also think time would be better spent standardising and polishing off existing features while improving the documentation as well. Anyway, if you don't mind I'm going to put the sideload and custom serializer issues to the side temporarily (anybody else is welcome to work on them). Instead I was thinking a few PRs regarding simplifying code and adding documentation/comments where
neccessary.

What do you think? Feel free to tell me to gtfo, I just feel solidifying existing features is better than adding new ones that could break things. If you're game then maybe we can create a issue listing all the things relating to a tidy up.

**Comment by brettshollenberger** [comment]
Nope, this is exactly where I am now. I've begun this already but it's a big undertaking; the whole codebase really needs to be restarted/restructured.

My primary concerns for the "real" 1.0.0 release of this are: 

1) Extensibility. E.g. adding custom parsers for new mime types and ability to describe fiat API standards. We need a more modular approach that will allow folks to sub in a simple function or provider to handle custom logic.

2) DRY this guy up. There's a ton of duplicated logic between the Base class methods which is making them very difficult to change. Similarly let's DRY up tests and split them into separate units. Everything's lumped together in this big hulking base class at the moment :) All my Ruby instincts are out the window in unfamiliar Javascript land. Maybe you'd be interested in writing and performing code reviews with me on a rewrite; it might help keep me organized. 

3) Hypermedia integration. I'd like to attempt to read hypermedia profiles (assuming anyone's using them) to establish custom API methods and documentation automatically (based on these profiles).

**Comment by brettshollenberger** [comment]
There's a ton on hypermedia integration. The best we can do for now is bow out when we know we don't understand a particular media type or don't see a profile, and offer documentation on how users can add that functionality to ActiveResource. Not many APIs are being written right now with hypermedia in mind, but if we want to write the future of client parser libraries, we need to get hypermedia right at some point.

**Comment by brayniverse** [comment]
I'm not familiar with hypermedia, care to share some reading material that you may have found helpful? Just so I can get an understanding of where you're coming from.

**Comment by brettshollenberger** [comment]
http://restfulwebapis.org, http://www.designinghypermediaapis.com, http://vimeo.com/53223942

**Comment by brettshollenberger** [comment]
RESTful Web APIs was my introduction. I fought pretty hard with the idea of hypermedia for a while, but it takes you through 8 chapters about it before you start designing hypermedia APIs, so it got me on board by then. Steve Klabnik's stuff is good once you're already a hypermedia acolyte.

**Comment by brayniverse** [comment]
Thanks for the material.

If it's okay with you I'm going to work on fragmenting `base.js` because at first glance that file is very daunting.

**Comment by brettshollenberger** [comment]
That's what I'm getting into as well. Good luck.

**Comment by brayniverse** [comment]
Lol I've split it up a little locally. So long as it compiles the same it shouldn't be an issue.

**Comment by brettshollenberger** [comment]
That's a good start. I think a lot of the primary methods should be re-written to allow for extension; I just setup a new mime type configuration module that I think is a good example of what I'm thinking; I'll share the branch later :)

**Comment by brayniverse** [comment]
Cool. Hopefully I'll have time to do some stuff tomorrow.

**Comment by brettshollenberger** [comment]
Hey @brayniverse, check out this working copy over here: 

https://github.com/brettshollenberger/ngactiveresource-refactor/blob/master/lib/base-class/mime/mime.js

Sorry the name is "BaseClass" instead of "ActiveResource." I started work on it as part of the egghead.io series and just decided to go full-on refactor in there since I was already re-building from scratch. So far it's proving fruitful; just have to keep applying the same level of attention to detail throughout the refactor and I think we'll have a better library.

The idea in the Mimetype module is fairly well explained, but one of the big impetuses here was your well-founded request for custom parsers for various APIs. The idea of the workflow in my mind here (once we get data from an API) is:

1) Grab "Content-Type" header
2) Send through Format parsers (e.g. "json", "xml") 
3) Send through MimeType parsers (e.g. "application/json" or "application/atom+xml") 
4) Send through Profile parsers (e.g. "hCard") 
5) Send through "Class Semantics" parsers (e.g. non machine-readable profile semantics dictated by the developer in code, or "gateway" modules for particular classes http://martinfowler.com/eaaCatalog/gateway.html). 
6) Hand off the parsed object to a subclass of ActiveResource.Base for instantiation

This gives us the ability to build in a few parsers for formats like XML and mimetypes like application/collection+json, and the developer the ability to add parsers for IANA registered microformats or their own proprietary semantics for skeezy APIs in need of some massaging.

**Comment by brayniverse** [comment]
Hey @brettshollenberger,

the documentation of that module is brilliant, it makes it much easier for a new developer to pickup and see excactly what you're doing.
The general flow of the module sounds great, one question, if the module parses the response object does Base offer the ability to manipulate data before the model is instantiated?

Also should I focus my attention on heling with the refactoring? Will it replace this repository or is it only for your egghead series?

**Comment by brettshollenberger** [comment]
I'm rebuilding in that directory right now. If there are particular modules you want to work on; let's talk about what they are and how the pieces fit together. Breaking out into these smaller pieces I think is helping with testing and extensibility, so let's keep in that direction. If it's easier, we can move it over to a branch in this repo. 

The ability to manipulate data before the model is instantiated is handled in that chain of parsers. The format parser chain (or mimetype parser chain if there's no underlying format) should return a Javascript object to work with in the Profile and Class Semantics parsers. So this is where I was recommending putting gateways that would need to interact with the data before it hit the new model instance.

**Comment by brayniverse** [comment]
I had a bit of time this morning and have began my efforts to help tidy up modules by splitting them into separate files / directories. I've got one question; I'm getting confused in the `validation.js` module where you have several functions which pass themselves as an argument (`min`, `max`, `requiredIf` etc). What's going on here? Can you explain it me so that I can document that up for future developers later?
