### ISSUE TITLE
Methods should more closely match RESTFUL endpoint schema

### ISSUE THREAD

**Issue by facultymatt** [FacultyCreative/ngActiveResource#5]
Currently the `find` methods limitation to a single object and lack of `show` method hinder proper API integration. 

The following API schema is expected: 

```
GET        /resource          Index page, lists all resources, returns array
POST       /resource          Create a new resource
GET        /resource/{id}     Get a single resource by id, returns object
PUT        /resource/{id}     Update a single resource by id
DELETE     /resource/{id}     Delete a single resource by id
GET        /resource/find     Finds many resources that match query params, returns array
```

However ngActiveResource deviates from this pattern which creates the following limitations: 
- Doesn't provide a show method. It forces the API to be designed to find by `id` from query params, rather then getting `id` from the url itself.
- `find()`, which you would expect to return an array in some cases, always returns a single object. This limits queries such as `posts/?published=true`.

This would require refactoring the methods `find()` and `where()` which would need to be discussed.

**Comment by facultymatt** [comment]
After our discussion it makes sense to leave endpoints as is and add a `show()` method that creates an array from the resource name and primary key.

**Comment by brettshollenberger** [comment]
This setup is currently supported. The findURL is whichever URL allows you the most flexibility--your /resource/find url. The methods provided by ActiveResource use this single endpoint to abstract the other use cases you describe. AR::Base#find will return a single instance, so you can provide it with either an id, or another parameter. AR::Base#where will return an array matching the parameters you pass, or all objects if you pass an empty object. $create and the createURL provide POST /resource; $delete and the deleteURL provide DELETE /resource/{id}, and $update and the updateURL provide PUT /resource/{id}. 

To find by id, you can use $routeParams to grab the id in the URL, and then use Model.find(id) to handle the find case. I see no reason to support redundancies like parameterized urls, since the query string is without limits, unlike a parameterized URL, which must explicitly define all cases. 

In order to handle the second use case, use Model#where, which returns an array.

**Comment by facultymatt** [comment]
I'm not suggesting support all possible combinations of a parameterized URL. I am suggesting that in some cases you will want to work with an API that expects the ResourceID to be present in the URL -- in these cases how does one setup ngActiveResouce to work with these APIs?

You suggest configuring `updateURL = /resource/{id}` etc - does ngActiveResource support the `{id}` pattern of replacement?

Considering this, perhaps the question at hand here is **can ngActiveResource be used with API's that require URL resource IDs?** Many popular APIs don't support sending query params in all cases, for example: http://instagram.com/developer/endpoints/users/. I understand this module was developed to work in situations where the developer controls the API, but in thinking outside these bounds to integrate with other popular APIs, URL based ID support would be helpful. 

Two questions I'm still left thinking about here, each one might be a good PR on its own: 
- Should ngActiveResource findURL, deleteURL, etc. accept {id} style definitions and replacement if the user configures them as such? 
- Should ngActiveResouce add a `show()` method which shows on resource item by id?

**Comment by brettshollenberger** [comment]
Sorry I forgot to close this; as you know, we've handled this now. The find method will now use the findURL; where method uses indexURL. URLs can be parameterized with colon-prefixed parameters e.g. users/:id
