### ISSUE TITLE
add more methods to resources

### ISSUE THREAD

**Issue by facultymatt** [FacultyCreative/ngActiveResource#8]
The following comes to mind, assuming a model called `Sensor`

```
Sensor.all(); // alternate way to write Sensor.where({})
Sensor.show(1); // alternate way to write Sensor.find(1) 
```

What other methods would be good to add?

**Comment by brettshollenberger** [comment]
Hey Matt-
Thanks for the recommendation. c9a8361bfba4a84c4a743551093e8863caf32532 adds `all`. It's a use case I see coming up often. Thanks for the idea for `show`, but I'd prefer not to implement an API of aliases at the moment. I'd prefer users of ActiveResource use it consistently, so that it might develop a de facto flavor of use, and that switching between apps that use it is easy and understandable. I'd prefer users not have to learn multiple APIs, as I think it could be confusing. 

Best,
Brett

**Comment by facultymatt** [comment]
Makes sense to me. Thanks for taking the time to consider the approach AND adding the all method.
